[project]
name = "subwayserver"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.120.0",
    "httpx>=0.28.1",
    "ngrok>=1.5.1",
    "anthropic>=0.26.0",
    "uvicorn>=0.38.0",
]
